### PR TITLE
Replace *nux-only arpreq with getmac

### PR DESCRIPTION
**Pull request by rec**
* See https://github.com/sebschrader/python-arpreq/issues/9
* Makes xled work on MacOS

Thanks for this very promising library!

I can't test this change with Linux, unfortunately, but it should work perfectly.  Can you patch it in to test perhaps?

### CODE REVIEW

**Comment by scrool** [comment]
Please see #18 and recently #52.

**Comment by scrool** [comment]
I'm currently thinking of an alternative workflow - see short description in #59.

**Comment by magicus** [comment]
I believe #63 makes this superfluous.

**Comment by scrool** [comment]
#63 has been merged so as @magicus said - this is now superfluous.

**Pull request closed without merging**
