### PR TITLE
Implement brightness management

### PR DESCRIPTION
**Pull request by timon**
This PR adds two methods to `xled.control` module: `get_brightness` and `set_brightness`

### CODE REVIEW

**Comment by timon** [comment]
Hey @scrool, the build failed for Python 2.7, is this still targeted?

**Comment by scrool** [comment]
> This PR adds two methods to `xled.control` module: `get_brightness` and `set_brightness`

Generally looks ok. I have updated changes to work with values 0.255. See my commit to your docs PR: https://github.com/scrool/xled-docs/pull/2#issuecomment-573455473 as well.

I guess it would be nice to enable/disable brightness without setting new value so I have modified xled's API to reflect those changes.

**Comment by scrool** [comment]
> Hey @scrool, the build failed for Python 2.7, is this still targeted?

Yes, unfortunately I haven't resolved issues with CI. Locally my tests against 2.7 still pass. 👍

**Comment by scrool** [comment]
Merged.

**Comment by timon** [comment]
Great, thanks!

**Pull request closed without merging**
