### PR TITLE
Add --mac cli option

### PR DESCRIPTION
**Pull request by PaulWebster**
Add --mac option in cli so that discovery can be by-passed

### CODE REVIEW

**Comment by olieter** [comment]
ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/setup.py'"'"'; __file__='"'"'/private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-wheel-bJhqbV
       cwd: /private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'arpreq' extension
  creating build
  creating build/temp.macosx-10.15-x86_64-2.7
  creating build/temp.macosx-10.15-x86_64-2.7/src
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/arpreq.c -o build/temp.macosx-10.15-x86_64-2.7/src/arpreq.o -std=c99
  src/arpreq.c:215:39: error: use of undeclared identifier 'SIOCGIFHWADDR'
                  if (ioctl(st->socket, SIOCGIFHWADDR, &ifreq) == -1) {
                                        ^
  src/arpreq.c:218:49: error: no member named 'ifr_hwaddr' in 'struct ifreq'
                      memcpy(&mac_address, &ifreq.ifr_hwaddr, sizeof(mac_address));
                                            ~~~~~ ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:63:33: note: expanded from macro 'memcpy'
                  __builtin___memcpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                ^~~~~~~~~~~
  src/arpreq.c:226:28: error: no member named 'arp_dev' in 'struct arpreq'
              strncpy(arpreq.arp_dev, ifa->ifa_name, IFNAMSIZ);
                      ~~~~~~ ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:128:28: note: expanded from macro 'strncpy'
                  __builtin___strncpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                           ^~~~
  src/arpreq.c:226:28: error: no member named 'arp_dev' in 'struct arpreq'
              strncpy(arpreq.arp_dev, ifa->ifa_name, IFNAMSIZ);
                      ~~~~~~ ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:128:62: note: expanded from macro 'strncpy'
                  __builtin___strncpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                                                             ^~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_common.h:39:54: note: expanded from macro '__darwin_obsz'
  #define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                       ^~~~~~
  src/arpreq.c:227:35: error: use of undeclared identifier 'SIOCGARP'
              if (ioctl(st->socket, SIOCGARP, &arpreq) == -1) {
                                    ^
  5 errors generated.
  error: command 'cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for arpreq
  Running setup.py clean for arpreq
Successfully built xled
Failed to build arpreq
Installing collected packages: arpreq, monotonic, pyzmq, backports-abc, futures, tornado, xled
    Running setup.py install for arpreq ... error
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/setup.py'"'"'; __file__='"'"'/private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-record-QAkkgv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/vjee/Library/Python/2.7/include/python2.7/arpreq
         cwd: /private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/
    Complete output (37 lines):
    running install
    running build
    running build_ext
    building 'arpreq' extension
    creating build
    creating build/temp.macosx-10.15-x86_64-2.7
    creating build/temp.macosx-10.15-x86_64-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/arpreq.c -o build/temp.macosx-10.15-x86_64-2.7/src/arpreq.o -std=c99
    src/arpreq.c:215:39: error: use of undeclared identifier 'SIOCGIFHWADDR'
                    if (ioctl(st->socket, SIOCGIFHWADDR, &ifreq) == -1) {
                                          ^
    src/arpreq.c:218:49: error: no member named 'ifr_hwaddr' in 'struct ifreq'
                        memcpy(&mac_address, &ifreq.ifr_hwaddr, sizeof(mac_address));
                                              ~~~~~ ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:63:33: note: expanded from macro 'memcpy'
                    __builtin___memcpy_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                                  ^~~~~~~~~~~
    src/arpreq.c:226:28: error: no member named 'arp_dev' in 'struct arpreq'
                strncpy(arpreq.arp_dev, ifa->ifa_name, IFNAMSIZ);
                        ~~~~~~ ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:128:28: note: expanded from macro 'strncpy'
                    __builtin___strncpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                             ^~~~
    src/arpreq.c:226:28: error: no member named 'arp_dev' in 'struct arpreq'
                strncpy(arpreq.arp_dev, ifa->ifa_name, IFNAMSIZ);
                        ~~~~~~ ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_string.h:128:62: note: expanded from macro 'strncpy'
                    __builtin___strncpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                                                               ^~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/secure/_common.h:39:54: note: expanded from macro '__darwin_obsz'
    #define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                         ^~~~~~
    src/arpreq.c:227:35: error: use of undeclared identifier 'SIOCGARP'
                if (ioctl(st->socket, SIOCGARP, &arpreq) == -1) {
                                      ^
    5 errors generated.
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/setup.py'"'"'; __file__='"'"'/private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-install-XrQqXv/arpreq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bh/fv5yblvn2f9_s4zl3v0tjm2w0000gn/T/pip-record-QAkkgv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/vjee/Library/Python/2.7/include/python2.7/arpreq Check the logs for full command output.

**Comment by PaulWebster** [comment]
This (old and unadopted) pull request is to add support for a MAC address parameter ... as in a low level networking attribute.
It is not for a MACintosh computer.
xled is not supported on Apple Mac.

**Comment by scrool** [comment]
I thought of this MR couple of times in the past. But I wasn't sure how to articulate what I didn't like about this approach.

The idea of CLI wasn't to expose all functionality of Twinkly library. I wanted to provide an interface that would be easy to use as opposed to a low level and configurable one. As an example option `--name` was intended to limit operation to a single of available devices.

I have added `--hostname` for a similar purpose but in the end I'm not happy about its existence. Primarily due to lower level nature of the option - IP address would play better with a discovery and human recognizable host name might not play well with DNS on a local network. On the top of that I didn't feel that `--hostname` added enough value to `--name`.

Up until recently I thought that primarily reason for `--mac` option was to speed up control by skipping discovery. But option goes even futher and require one to operate on much lower level.

Recently I ended up in a situation where ARP requests doesn't seem to be propagated across networks (for obvious reasons) but IP packets are forwarded just fine. In that case some kind of specification of MAC address might be useful so I have thought to use #59 for that as well (on the top decision to use either `getmac` and `arpreq` or both).

Change of the workflow doesn't necesarily remove discovery though. But with that being implemented it might help to resolve other issue - see #61.

**Comment by magicus** [comment]
The fix in #63 makes it possible to extract the IP address from the device itself. This does not eliminate the need for discovery by broadcasting, but I assume that it does eliminate the problem that this PR wanted to solve.

**Comment by PaulWebster** [comment]
I really don't mind if my change is accepted - in any case I can still run it locally.
The reason for me skipping the discovery stage is to make the cli operation faster.

So - a bit more about that. Example below with real MAC replaced.

$ time /home/pi/twinkly/runxled.py --hostname=192.168.2.202 --mac=aa:bb:cc:dd:ee:ff get-mode
Looking for device with address: 192.168.2.202...
Device in mode movie.

real    0m3.077s
user    0m2.860s
sys     0m0.140s

$ time /home/pi/twinkly/runxled.py --hostname=192.168.2.202  get-mode
Looking for device with address: 192.168.2.202...
Device in mode movie.

real    0m5.031s
user    0m2.820s
sys     0m0.170s

For me it saves around 2 seconds - that is not much in the grand scheme of things, especially if the Python application is long running and the discovered MAC address is preserved ... but for cli where a script or other application is doing the calling then 2 more seconds is a long time to hang around ... especially when, in my case, there are other non-Twinkly lights that are being set to the same colour at the same time.
For me the Twinkly lights are in the Christmas tree at Christmas but are reused as above cupboard lighting for the rest of the year and other lights perform similar function elsewhere in the room.

**Comment by scrool** [comment]
I think #61 should cover your use case to speedup operations as well. If you think otherwise please comment or reopen #14.

**Pull request closed without merging**
